spring:
  datasource:
    driverClassName: org.h2.Driver
    platform: h2
    url: jdbc:h2:mem:sixletterwordsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MYSQL
    username: sa
    password: password
  h2:
    console:
      enabled: true

okta:
  oauth2:
    issuer: https://mycompany.okta.com/oauth2/bvtb1ndpsmqAKj1D51i8
    audience: https://mycompany.okta.com
    client-id: mycompany.mt-slwa
