---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: default
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
    alb.ingress.kubernetes.io/healthcheck-port: "8080"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/group.name: "six-letter-words-api"
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: "/*"
            backend:
              serviceName: {{ .Chart.Name }}
              servicePort: http
